const data = {
  products: [
    {
      _id: "1",
      name: "Case para PC",
      category: "Case",
      image: "/images/p1.jpg",
      price: 30,
      countInStock: 10,
      brand: "Cooler Master",
      rating: 4.5,
      numReviews: 10,
      description: "Un case melardo",
    },
    {
      _id: "2",
      name: "Mouse Logitech",
      category: "Mice",
      image: "/images/p2.jpg",
      price: 45,
      countInStock: 20,
      brand: "Logitech",
      rating: 5,
      numReviews: 4,
      description: "Un mouse melardo",
    },
    {
      _id: "3",
      name: "Teclado Redragon",
      category: "Keyboard",
      image: "/images/p3.jpg",
      price: 60,
      countInStock: 0,
      brand: "Redragon",
      rating: 4.5,
      numReviews: 10,
      description: "Un teclado melardo",
    },
    {
      _id: "4",
      name: "Headset Cooler Master",
      category: "Headset",
      image: "/images/p4.jpg",
      price: 30,
      countInStock: 15,
      brand: "Cooler Master",
      rating: 4.5,
      numReviews: 10,
      description: "Un headset melardo",
    },
    {
      _id: "5",
      name: "Procesador Ryzen 5",
      category: "Proccess",
      image: "/images/p5.jpg",
      price: 30,
      countInStock: 5,
      brand: "Ryzen",
      rating: 4.5,
      numReviews: 10,
      description: "Un procesador melardo",
    },
    {
      _id: "6",
      name: "Monitor Asus 24inch",
      category: "Monitors",
      image: "/images/p6.jpg",
      price: 150,
      countInStock: 2,
      brand: "Asus",
      rating: 4.5,
      numReviews: 10,
      description: "Un monitor melardo",
    },
  ],
};

export default data;
